version: "3.5"
networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}
services:
  httpd:
    container_name: httpd
    build:
      context: ./httpd
      args:
        - HTDOCS_PATH=${HTTPD_DOCUMENT_ROOT}/default
    volumes:
      - ${HOST_SOURCE_PATH}:${HTTPD_DOCUMENT_ROOT}
      - ${HOST_CONTAINER_DATA}${HTTPD_CONF_PATH}/:/usr/local/apache2/conf/
      - ${HOST_CONTAINER_DATA}${HTTPD_HOST_LOG_PATH}:/usr/local/apache2/logs/
    ports:
      - "${HTTPD_HOST_HTTP_PORT}:80"
      - "${HTTPD_HOST_HTTPS_PORT}:443"
    networks:
      - frontend
      - backend
  php7:
    container_name: php7
    build:
      context: ./php7
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${HOST_SOURCE_PATH}:${HTTPD_DOCUMENT_ROOT}
    ports:
      - "${PHP7_HOST_XDEBUG_PORT}:9000"
    networks:
      - backend
  mariadb:
    container_name: mariadb
    build:
      context: ./mariadb
      args:
          - http_proxy
          - https_proxy
          - no_proxy
          - MARIADB_VERSION=${MARIADB_VERSION}
    volumes:
        - ${HOST_CONTAINER_DATA}/mariadb:/var/lib/mysql
        - ${MARIADB_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
        - "${MARIADB_PORT}:3306"
    environment:
        - TZ=${TIMEZONE}
        - MYSQL_DATABASE=${MARIADB_DATABASE}
        - MYSQL_USER=${MARIADB_USER}
        - MYSQL_PASSWORD=${MARIADB_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    networks:
      - backend
  node:
    container_name: node
    build:
      context: ./node
    volumes:
      - ${HOST_SOURCE_PATH}:${HTTPD_DOCUMENT_ROOT}
    ports:
      - "${NODE_HOST_PORT}:3000"
    networks:
      - backend
    links:
      - httpd:*.test
  workspace:
    container_name: workspace
    build:
      context: ./workspace
    volumes:
      - ${HOST_SOURCE_PATH}:${HTTPD_DOCUMENT_ROOT}
    networks:
      - backend